version: '3.4'

services:
  dockermicroservice:
    image: ${DOCKER_REGISTRY-}dockermicroservice
    build:
      context: .
      dockerfile: DockerMicroservice/Dockerfile
    depends_on:
      - db_service
    networks:
      - db-network

  db_service: 
    container_name: db_service
    image: postgres:latest  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2345
      - POSTGRES_DB=MicroserviceDockerDB
    volumes:
      - pgdata:/var/lib/postgresql/MicroserviceDockerDB
    ports:
      - "5433:5432"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  pgdata: